### ISSUE TITLE
SCL cock stretching

### ISSUE THREAD

**Issue by anna-oake** [pasko-zh/brzo_i2c#46]
Hey, thanks for your great work!
I've installed the library, but can't get [the cock stretching](https://github.com/pasko-zh/brzo_i2c/wiki#why-implement-i2c-for-the-esp8266-in-assembly) feature to work.
Is it really supported?

---

<img width="929" alt="image" src="https://user-images.githubusercontent.com/2043497/132994569-8120a291-4d72-49c0-b942-4c4ea8df0b39.png">

**Comment by valkuc** [comment]
Yeah :D Cock Stretching - that's interesting technology... promising :D

**Comment by pasko-zh** [comment]
:-D

**Comment by pasko-zh** [comment]
typo corrected
